apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xbasecomponentskcl.consumable.trustbank.sg
spec:
  group: consumable.trustbank.sg
  names:
    kind: xBaseComponentKcl
    plural: xbasecomponentskcl
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              eksClusterRef:
                type: string
                description: "Reference to the EksCluster claim name (e.g. 'eksac-cluster01') to deploy components to"
              namespace:
                type: string
                default: "default"
                description: "Default namespace for components"
              baseComponents:
                type: object
                properties:
                  certManager:
                    type: object
                    properties:
                      version:
                        type: string
                  adot:
                    type: object
                    description: "AWS Distro for OpenTelemetry EKS add-on - only installed if specified"
                    properties:
                      version:
                        type: string
                        description: "ADOT add-on version (required, e.g., 'v0.88.0-eksbuild.1')"
                    required:
                    - version
                  awsEbsCsiDriver:
                    type: object
                    description: "AWS EBS CSI Driver EKS add-on - only installed if specified"
                    properties:
                      version:
                        type: string
                        description: "AWS EBS CSI Driver add-on version (required, e.g., 'v1.35.0-eksbuild.1')"
                    required:
                    - version
            required:
            - eksClusterRef
          status:
            type: object
            properties:
              installedComponents:
                type: array
                items:
                  type: string
              ready:
                type: boolean
    served: true
    referenceable: true
  claimNames:
    kind: BaseComponent
    plural: basecomponents 