apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xbasecomponentskcl.consumable.trustbank.sg
spec:
  group: consumable.trustbank.sg
  names:
    kind: xBaseComponentKcl
    plural: xbasecomponentskcl
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              eksClusterRef:
                type: string
                description: "Reference to the EksCluster claim name (e.g. 'eksac-cluster01') to deploy components to"
              awsAccountId:
                type: string
                description: "AWS Account ID where the EKS cluster is deployed"
              namespace:
                type: string
                default: "default"
                description: "Default namespace for components"
              eksAddons:
                type: array
                description: "List of EKS addons to install"
                items:
                  type: object
                  properties:
                    name:
                      type: string
                      description: "EKS addon name (e.g., 'adot', 'aws-ebs-csi-driver', 'eks-pod-identity-agent', 'aws-efs-csi-driver')"
                    version:
                      type: string
                      description: "EKS addon version (e.g., 'v0.88.0-eksbuild.1')"
                    configurationValues:
                      type: object
                      description: "Optional configuration values for the addon"
                      x-kubernetes-preserve-unknown-fields: true
                  required:
                  - name
                  - version
            required:
            - eksClusterRef
            - awsAccountId
          status:
            type: object
            properties:
              installedAddons:
                type: array
                items:
                  type: string
              ready:
                type: boolean
    served: true
    referenceable: true
  claimNames:
    kind: BaseComponent
    plural: basecomponents