{{- with .Values.provider.awsFamily }}
apiVersion: pkg.crossplane.io/v1beta1
kind: DeploymentRuntimeConfig
metadata:
  name: {{ .deploymentRuntimeConfig.name }}
spec:
  deploymentTemplate:
    spec:
      replicas: {{ .deploymentRuntimeConfig.deploymentTemplate.spec.replicas }}
      selector: {}
      template:
        spec:
          containers:
          - name: package-runtime
            args:
            - --enable-external-secret-stores
      #   spec:
      #     securityContext:
      #       runAsNonRoot: true
      #       runAsUser: 2000
      #       runAsGroup: 2000
      #     containers:
      #     - env:
      #       - name: AWS_STS_REGIONAL_ENDPOINTS
      #         value: regional
      #       - name: AWS_DEFAULT_REGION
      #         value: {{ .region }}
      #       - name: AWS_REGION
      #         value: {{ .region }}
      #       - name: AWS_ROLE_ARN
      #         value: arn:aws:iam::{{ .accountId }}:role/{{ .crossplaneIamRoleName }}
      #       - name: AWS_WEB_IDENTITY_TOKEN_FILE
      #         value: /var/run/secrets/eks.amazonaws.com/serviceaccount/token
      #       name: package-runtime
      #       volumeMounts:
      #       - mountPath: /var/run/secrets/eks.amazonaws.com/serviceaccount
      #         name: aws-iam-token
      #         readOnly: true
      #     volumes:
      #     - name: aws-iam-token
      #       projected:
      #         defaultMode: 420
      #         sources:
      #         - serviceAccountToken:
      #             audience: sts.amazonaws.com
      #             expirationSeconds: 86400
      #             path: token
  serviceAccountTemplate:
    metadata:
      annotations:
        eks.amazonaws.com/role-arn: arn:aws:iam::{{ .accountId }}:role/{{ .crossplaneIamRoleName }}
{{- end }}