apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xnetworksv2.consumable.trustbank.sg
spec:
  group: consumable.trustbank.sg
  names:
    kind: xNetworkV2
    plural: xnetworksv2
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              name:
                type: string
              location:
                type: string
                oneOf:
                - pattern: '^ap-southeast-1$'
              vpcCidr:
                type: string
              subnets:
                type: object
                properties:
                  public:
                    type: object
                    properties:
                      z1Cidr:
                        type: string
                      z2Cidr:
                        type: string
                      z3Cidr:
                        type: string
            required:
            - name
          status:
            type: object
            properties:
              natGatewayId:
                type: string
    served: true
    referenceable: true 