apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xnetworksgov2.consumable.trustbank.sg
spec:
  group: consumable.trustbank.sg
  names:
    kind: xNetworkGoV2
    plural: xnetworksgov2
  scope: Cluster
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              # Standard Crossplane fields
              compositionRef:
                type: object
                properties:
                  name:
                    type: string
                required:
                - name
              compositionRevisionRef:
                type: object
                properties:
                  name:
                    type: string
                required:
                - name
              compositionUpdatePolicy:
                type: string
                enum:
                - Automatic
                - Manual
              # Custom fields
              name:
                type: string
              location:
                type: string
                oneOf:
                - pattern: '^ap-southeast-1$'
              vpcCidr:
                type: string
              subnets:
                type: object
                properties:
                  public:
                    type: object
                    properties:
                      1a:
                        type: string
                      1b:
                        type: string
                      1c:
                        type: string
            required:
            - name
          status:
            type: object
            properties:
              natGatewayId:
                type: string
    served: true
    referenceable: true