apiVersion: consumable.trustbank.sg/v1alpha1
kind: BaseComponent
metadata:
  name: andy-cluster-base-components
  namespace: eksac
spec:
  eksClusterRef: "andy-cluster"
  namespace: "eksac"
  baseComponents:
    certManager:
      version: "v1.13.3"
    # adot:
    #   version: "v0.117.0-eksbuild.1"
    awsEbsCsiDriver:
      version: "v1.46.0-eksbuild.1"
    # eksPodIdentityAgent:
    #   version: "v1.0.0-eksbuild.1" 