apiVersion: consumable.trustbank.sg/v1alpha1
kind: BaseComponent
metadata:
  name: andy-cluster-base-components
  namespace: eksac
spec:
  eksClusterRef: "andy-cluster"
  awsAccountId: "249140151390" # Replace with your AWS account ID
  namespace: "eksac"
  # eksAddons:
  # - name: "eks-pod-identity-agent"
  #   version: "v1.0.0-eksbuild.1"
