apiVersion: consumable.trustbank.sg/v1alpha1
kind: BaseComponent
metadata:
  name: my-base-components
  namespace: eksac
spec:
  eksClusterRef: "eksac-cluster01"
  namespace: "default"
  baseComponents:
    certManager:
      version: "v1.13.2" 