apiVersion: consumable.trustbank.sg/v1alpha1
kind: BaseComponent
metadata:
  name: andy-cluster-base-components
  namespace: eksac
spec:
  eksClusterRef: "andy-cluster"
  namespace: "eksac"
  baseComponents:
    certManager:
      version: "v1.13.3" 