apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xeksclustersv3.consumable.trustbank.sg
spec:
  group: consumable.trustbank.sg
  names:
    kind: xEksClusterV3
    plural: xeksclustersv3
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              name:
                type: string
              location:
                type: string
                oneOf:
                - pattern: '^ap-southeast-1$'
              awsAccountId:
                type: string
              vpcRef:
                type: string
              subnets:
                type: object
                properties:
                  private:
                    type: object
                    properties:
                      1a:
                        type: string
                      1b:
                        type: string
                      1c:
                        type: string
              components:
                type: object
                properties:
                  ciliumHelm:
                    type: object
                    properties:
                      version:
                        type: string
                  corednsHelm:
                    type: object
                    properties:
                      version:
                        type: string
                  eks:
                    type: object
                    properties:
                      version:
                        type: string
                  karpenterHelm:
                    type: object
                    properties:
                      version:
                        type: string
                  argocdHelm:
                    type: object
                    properties:
                      version:
                        type: string
            required:
            - name
          status:
            type: object
            properties:
              oidcIssuer:
                type: string
              clusterEndpoint:
                type: string
              karpenterFargateStatus:
                type: string
    served: true
    referenceable: true
  claimNames:
    kind: EksClusterV3
    plural: eksclustersv3