apiVersion: v2
name: crossplane-providers-chart
description: A Helm chart for Crossplane Providers with support for both EKS (IRSA) and local Kind (secrets) deployments
type: application
version: "0.2.0"
appVersion: "0.2.0"
