provider:
  awsFamily:
    name: aws-provider
    accountId: "390945758345"  # Replace with your AWS account ID
    crossplaneIamRoleName: "eksac-crossplane-iam-role"
    region: ap-southeast-1
    deploymentRuntimeConfig:
      name: aws-deployment-runtime-config
      deploymentTemplate:
        spec:
          replicas: 1
    version: v1
    
    # Deployment mode configuration
    # Options: "eks" (for EKS with IRSA) or "local" (for local Kind with secrets)
    # Default: "eks"
    deploymentMode: "eks"
    
    # Configuration for local Kind deployment (only used when deploymentMode: "local")
    localConfig:
      # AWS secret configuration (user must create this manually)
      # kubectl create secret generic aws-secret -n crossplane-system --from-file=creds=./01-aws-credentials.txt
      secretName: "aws-secret"
      secretNamespace: "crossplane-system"
      secretKey: "creds"
      # Optional: Use assumeRoleChain for better security (recommended for production)
      enableAssumeRole: true
      # assumeRoleArn will be constructed from accountId and crossplaneIamRoleName above
    
    providers:
    - name: provider-aws-ec2
      providerConfig:
        credentials:
          source: IRSA  # Used when deploymentMode: "eks"
    - name: provider-aws-eks
      providerConfig:
        credentials:
          source: IRSA  # Used when deploymentMode: "eks"
    - name: provider-aws-iam
      providerConfig:
        credentials:
          source: IRSA  # Used when deploymentMode: "eks"
  helm:
    version: v0
  kubernetes:
    version: v0
    providers:
    - name: provider-kubernetes
      providerConfig:
        credentials:
          source: InjectedIdentity

function:
  kcl:
    version: v0.11.4
  autoready:
    version: v0.4.2
  sequencer:
    version: v0.2.3