provider:
  awsFamily:
    name: aws-provider
    accountId: "249140151390"  # Replace with your AWS account ID
    crossplaneIamRoleName: "CrossPlaneRole"
    region: ap-southeast-1
    deploymentRuntimeConfig:
      name: aws-deployment-runtime-config
      deploymentTemplate:
        spec:
          replicas: 1
    version: v1.23.1
    
    # Set deployment mode to local for Kind clusters
    deploymentMode: "local"
    
    # Configuration for local Kind deployment
    localConfig:
      # AWS secret configuration (user must create this manually)
      # kubectl create secret generic aws-secret -n crossplane-system --from-file=creds=./01-aws-credentials.txt
      secretName: "aws-secret"
      secretNamespace: "crossplane-system"
      secretKey: "creds"
      # Use assumeRoleChain for better security (recommended)
      enableAssumeRole: true
    
    providers:
    - name: provider-aws-ec2
      providerConfig:
        credentials:
          source: IRSA  # This will be overridden by deploymentMode setting
    - name: provider-aws-eks
      providerConfig:
        credentials:
          source: IRSA  # This will be overridden by deploymentMode setting
    - name: provider-aws-iam
      providerConfig:
        credentials:
          source: IRSA  # This will be overridden by deploymentMode setting
    - name: provider-aws-secretsmanager
      providerConfig:
        credentials:
          source: IRSA  # This will be overridden by deploymentMode setting
    - name: provider-aws-s3
      providerConfig:
        credentials:
          source: IRSA  # This will be overridden by deploymentMode setting
    - name: provider-aws-efs
      providerConfig:
        credentials:
          source: IRSA  # This will be overridden by deploymentMode setting
  helm:
    version: v0
  kubernetes:
    version: v0
    providers:
    - name: provider-kubernetes
      providerConfig:
        credentials:
          source: InjectedIdentity

function:
  kcl:
    version: v0.11.4
  autoready:
    version: v0.4.2
  sequencer:
    version: v0.2.3 